### ISSUE TITLE
I need to put my table to slider-concave

### ISSUE THREAD

**Issue by eotaoza** [lukeed/bee3d#34]
Hi folks!
I need put my table to slider-concave && it's possible use slider on any tags? Thx a lot.

**Comment by lukeed** [comment]
Hi there,

What have you tried?

It's just like anything else, but instead of "regular" content, you put in your table markup. 

> **Note:** You will have to style your table to how you want it. Bee3D did not and does not come with any table styles.

``` html
<div id="demo" class="bee3D--parent">
    <section class="bee3D--slide">Slide 1</section>
    <section class="bee3D--slide">
        <table class="my-table">
            <!-- your table stuff -->
        </table>
    </section>
    <section class="bee3D--slide">Slide 3</section>
  </div>

<!-- At bottom of page -->
<script src="scripts/dependencies/classie.js"></script>
<script src="scripts/bee3D.min.js"></script>

<!-- Now we create a new slider -->
<script>
  var demo = document.getElementById('demo');

  var slider = new Bee3D(demo, {
    effect: 'concave',
    // ... more options here
  });
</script>
```

**Comment by eotaoza** [comment]
Thank you very much, could you say me please how to manipulate with **after-1** in concave > section > table with id concave_table1 ? Because for example, i did before-1 and active(current) section how me need and **after-1 slide**  spreads in height and width(very big sized in comparison with before-1 and current )
Of course i tried fix in the bee3D.css
this strings (i have it now) ->

``` css
.bee3D--effect__concave .bee3D--before {
    transform: translateX(-800px) rotateY(90deg) translateX(-800px);
    opacity: 0.35; 
}
.bee3D--effect__concave .bee3D--before-1 {
    transform: translateX(-310px) rotateY(28deg) translateX(-240px);
    opacity: 0.35; 
}
.bee3D--effect__concave .bee3D--after {
  transform: translateX(800px) rotateY(-90deg) translateX(800px);
  opacity: 0.35; 
}
.bee3D--effect__concave .bee3D--after-1 {
    transform: translateX(310px) rotateY(-28deg) translateX(240px);
    opacity: 0.35; 
}
```
