### ISSUE TITLE
Concave infinite scroll html page

### ISSUE THREAD

**Issue by alexey13** [lukeed/bee3d#56]
Good day! As you can see when we use that effect page have scroll but it should not. https://www.lukeed.com/demo/bee3D/#/effects/concave

**Comment by alexey13** [comment]
Hello!:)))

**Comment by lukeed** [comment]
Hi, sorry 🙈 

Not sure what the issue is or what you're trying to say. Can you explain more?

**Comment by alexey13** [comment]
![-1](https://user-images.githubusercontent.com/4134234/30786955-67ccfca8-a187-11e7-9284-c0a11a6e6f4a.jpg)
Endless scroll

**Comment by lukeed** [comment]
Have never seen that before. What browser and browser version?

Try adding this:

```css
#main { height:100vh }
.bee3D--parent { overflow:hidden }
```

**Comment by alexey13** [comment]
its mozilla firefox, last one

**Comment by lukeed** [comment]
Ah, just tested.

Luckily, it's just demo code. Adding this solves it:

```css
#main { overflow:hidden }
```
